### ISSUE TITLE
Complex Layouts

### ISSUE THREAD

**Issue by PaulWoitaschek** [tumblr/Graywater#3]
I have a question about building more complex layout. In your example the layout is very basic with elements under each other.

How could one build more complex layouts? Let's say we have a List of `CardView`s and in these CardViews, there are different layouts of Text, Images, Buttons etc.

Does that setup work with Graywater? It would be great if you could add a sample with real layouts and not just views.

**Comment by ericleong** [comment]
Unfortunately this framework was built with the idea that you can decompose your layouts by drawing a horizontal line (in a vertical list) to separate each "section". The issue with the `CardView`  layout is that everything inside the card needs to be inside the `CardView` - when you inflate the layout, all the views inside also need to be inflated.

If you want to use this library, I would recommend "faking" the card by using different backgrounds for the different parts of the card. Unfortunately this means you lose the ripple effect across the entire card.

There are other solutions that involve `ViewStub` or pre-inflating views with [`AsyncLayoutInflater`](https://developer.android.com/reference/android/support/v4/view/AsyncLayoutInflater.html), but it's tricky to do right.

I would recommend taking a look at [Litho](https://fblitho.com/) if you need a library that handles fine-grained recycling.

**Comment by PaulWoitaschek** [comment]
Thanks for the explanation. How would you use `AsyncLayoutInflater` with RecyclerView? 

I find Litho interesting, however I find it way to special to include it in a customer project as the coupling to the library is extremely high when you start using it.

**Comment by ericleong** [comment]
Ah, you shouldn't use `AsyncLayoutInflater` with `RecyclerView` 😉 

`RecyclerView`, in fact, already prefetches views via [`RecyclerView.LayoutManager#setItemPrefetchEnabled(boolean)`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.LayoutManager.html#setItemPrefetchEnabled(boolean)) - you can read more about it in [this blog post](https://medium.com/google-developers/recyclerview-prefetch-c2f269075710).

One possibility for fine-grained recycling without Litho is to write a custom `LayoutManager` that understands layouts - think of it like using a `GridLayoutManager` with spans to imitate a more complex layout. Unfortunately, writing a custom `LayoutManager` is a lot of work for very specific behavior, and even Litho (which uses a different system) doesn't cover all cases.
